---
- name: Configure Smart Licensing 
  connection: local
  hosts: "{{ hostname }}"
  gather_facts: false
  vars_files: 
    - idtoken.yml
    - secrets.yml
  vars:
    provider:
      host: "{{ public_ip }}"
      username: "{{ username }} "
      ssh_keyfile: "{{ ssh_keyfile }}"

  tasks:
    - name: Enable Smart License
      ios_config:
        lines: license smart enable
        provider: "{{ provider }}"
      notify:
        - write config

    - name: Configure DNS Server
      ios_config:
        lines: ip name-server 8.8.8.8
        provider: "{{ provider }}"
      notify:
        - write config

    - name: Register with CSSM
      ios_command:
        commands: "license smart register idtoken {{ idtoken }}"
        provider: "{{ provider }}"
      register: status1

    - debug: "msg='Registration Status: {{ status1.stdout_lines[0][1] }}'"
    
    - name: Enable AX 2.5G License
      ios_config:
        lines: 
          - license boot level ax
          - platform hardware throughput level MB 2500
        provider: "{{ provider }}"
      notify:
        - write config    

    - name: Waiting for 10 seconds
      wait_for: timeout=10

    - name: Check Smart License Status
      ios_command:
        commands: show license summary
        provider: "{{ provider }}"
      register: status2

    - debug: var=status2.stdout_lines

  handlers:
    - name: write config
      ios_command:
        commands: write
        provider: "{{ provider }}"

