---    
- name: Configure AWS HA 
  connection: local
  hosts: aws
  gather_facts: false
  vars_files: 
    - secrets.yml
  vars:
    provider:
      host: "{{ public_ip }}"
      username: "{{ username }}"
      ssh_keyfile: "{{ ssh_keyfile }}"

  pre_tasks:
    - name: Backup Config
      ios_template:
        backup: true
        src: backupconfig.j2
        provider: "{{ provider }}"

  tasks:
    - name: HA EEM Configuration
      ios_template:
        src: eem.j2
        provider: "{{ provider }}"
      notify:
        - write config

    - name: HA GRE Configuration
      ios_template:
        src: gre.j2
        provider: "{{ provider }}"
      notify:
        - write config

    - name: HA EIGRP Configuration
      ios_template:
        src: eigrp.j2
        provider: "{{ provider }}"
      notify:
        - write config

    - name: HA Static Default Route Configuration
      ios_template:
        src: staticdefault.j2
        provider: "{{ provider }}"
      notify:
        - write config

    - name: HA Static IP Address Configuration
      ios_template:
        src: staticip.j2
        provider: "{{ provider }}"
      notify:
        - write config
  
  handlers:
    - name: write config
      ios_command:
        commands: write
        provider: "{{ provider }}"
