---
- name: IOS CLI PLaybook
  hosts: aws
  gather_facts: no
  connection: local

  tasks:
    - name: set provider
      set_fact: 
        provider:
          host: "{{ public_ip }}"
          username: ec2-user
          ssh_keyfile: /Users/chocker/Documents/Tech/Cloud/CSR1K-AWS/chockerva-fedcsn.pem
    
    - name: Run Exec Command
      ios_command:
        provider: "{{ provider }}"
        commands:
          - "{{ command }}"
      register: output
   
    - debug: var=output.stdout_lines
